[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

# Netlify Configuration for Static Site Deployment
[build]
  command = "bun run build"
  publish = "dist"

# Handle SPA routing for React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable Brotli and Gzip compression
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https://*.unsplash.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self'"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=31536000, immutable"
